### PR TITLE
Acuant: return PII even when there are errors

### PR DESCRIPTION
**Pull request by zachmargolis**
**Why**: So we can conditionally pass people with certain
errors in the IDP

For: https://github.com/18F/identity-idp/pull/5082

### CODE REVIEW

**Comment by aduth** [comment]
Do we need to update this for LN as well?

https://github.com/18F/identity-doc-auth/blob/204ca459221bd9e0a42c2cc51041adc90940de9b/lib/identity_doc_auth/lexis_nexis/responses/true_id_response.rb#L65

**Comment by zachmargolis** [comment]
> Do we need to update this for LN as well?

I believe the LN will behave fine as-is, because this is still technically a failure case (because of a hard fail on expiration). Then, the errors will be not-empty and show what we expect. The LN `pii_from_doc` doesn't have the same short-circuit logic that our Acuant code had (hence this PR)

**Comment by aduth** [comment]
> > Do we need to update this for LN as well?
> 
> I believe the LN will behave fine as-is, because this is still technically a failure case (because of a hard fail on expiration). Then, the errors will be not-empty and show what we expect. The LN `pii_from_doc` doesn't have the same short-circuit logic that our Acuant code had (hence this PR)

Ah, yeah, you're right, I totally misread this 👍

**Review by aduth — APPROVED** [review]
👍

**Review by stevegsa — APPROVED** [review]
LGTM

**Pull request merged**
